# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20171216_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='relation_to_denis',
            field=models.CharField(choices=[('H', 'Ненависть'), ('U', 'Не знаком')], default='H', max_length=1),
        ),
    ]
